spring.datasource.url=jdbc:postgresql://localhost:5432/week3db
spring.datasource.username=katie
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect